# Generated by Django 4.0.4 on 2023-08-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codexio_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
